jwt:
  secret: 984hg493grt67m6thr0429uruj2309yh9gjhc763fe87t3f89723gf
  lifetime: 300m
spring:
  mail:
    host: smtp.yandex.ru
    username: planningservice@yandex.ru
    password: nxxgejwxwnzxekbe
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/MeetingPlanningService
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
